apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scenario-server
  name: scenario-server
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: scenario-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scenario-server
    spec:
      containers:
        - image: jwfeb05/jw-home-scenario-server:latest
          imagePullPolicy: Always
          name: scenario-server
          ports:
            - containerPort: 9094
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_PORT
            - name: MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_USER
            - name: MONGODB_PASS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_PASS
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MYSQL_PASS
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: scenario-server
  name: scenario-server
  namespace: default
spec:
  ports:
    - port: 9094 #CHANGE
      protocol: TCP
      targetPort: 9094 #CHANGE
  selector:
    app: scenario-server
  sessionAffinity: None #CHANGE
  type: NodePort