server:
  port: 9094
spring:
  data:
    mongodb:
      uri: mongodb://user:pass@url:27017/jw-home?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      authentication-database: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: username
    password: password
    hikari:
      minimum-idle: 20
      maximum-pool-size: 30
      idle-timeout: 590000
      max-lifetime: 590000
  jpa:
    show-sql: true
  quartz:
    job-store-type: jdbc
    scheduler-name: JWHOME-Scheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 50
            threadNamePrefix: QuartzScheduler
          jobStore:
            tablePrefix: QRTZ_
            isClustered: true
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: true
            misfireThreshold: 60000
client:
  api-server:
    url: http://localhost:9092