server:
  port: 9094
spring:
  application:
    name: scenario-server
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:admin}:${MONGODB_PASS:pass}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/jw-home?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      authentication-database: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/quartz?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASS:pass}
    hikari:
      minimum-idle: 20
      maximum-pool-size: 30
      idle-timeout: 590000
      max-lifetime: 590000
  jpa:
    show-sql: true
  quartz:
    job-store-type: jdbc
    scheduler-name: JWHOME-Scheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 50
            threadNamePrefix: QuartzScheduler
          jobStore:
            tablePrefix: QRTZ_
            isClustered: true
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: true
            misfireThreshold: 60000
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://127.0.0.1:8761/eureka}